name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

env:
  CONDA_DLL_SEARCH_MODIFICATION_ENABLE: 1

jobs:
  build-cross-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install mamba
      run: |
        conda install -c conda-forge mamba
    - name: Install dependencies
      run: |
        mamba env update --file environment-test.yml --name base
    - name: Install current project in dev mode
      run: |
        pip install -e .
    - name: Install pytest
      run: |
        mamba install -c conda-forge pytest
    - name: Test ImageJ2 + original ImageJ
      run: |
        pytest test/ -p no:faulthandler
    - name: Test ImageJ2 standalone
      run: |
        pytest test/ -p no:faulthandler --legacy=false
    - name: Test Fiji Is Just ImageJ(2)
      run: |
        pytest test/ -p no:faulthandler --ij=sc.fiji:fiji
